version: '3.9'

services:
  hs-app:
    image: homestuff:0.0.1
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: hs-db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - hs-db

  hs-db:
    container_name: hs-db
    image: mysql:8.0.26
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: household_things_inventory
      MYSQL_ROOT_PASSWORD: root